---
title: "*NCSTN* knockdown with different shRNAs"
author: "Elisha Roberson"
date: "March 2, 2018"
output: html_document
---

Five shRNA constructs were tested in HEK001 and HEK293 to determine the optimal construct for knockdown selection.

```{r libraries}
library( here )
library( plyr )
library( dplyr )
library( ggplot2 )
library( reshape2 )
library( stringr )
library( readr )
```

```{r source_it}
source( here::here( 'code', "ncstn_knockdown_fxns.R" ) )
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message=FALSE,
	fig.path=paste0( output_figure_rel_dir, "/" ),
	fig.keep='all',
	dpi=300,
	fig.width=11,
	fig.height=8.5 )
```

## Import data
```{r read_data}
shrna_rtqpcr <- read_csv( knockdown_prepuro_rtqpcr, col_names=TRUE ) %>%
	mutate( Cell_Line = factor( Cell_Line, levels=c( "HEK001", "HEK293" ) ) ) %>%
	mutate( Construct = factor( Construct, levels=c( "control", "A06", "A07", "A08", "A09", "A10" ) ) ) %>%
	mutate( Amplicon = ifelse( Amplicon == "Amplicon_1", "NCSTN_1", Amplicon ) ) %>%
	mutate( Amplicon = ifelse( Amplicon == "Amplicon_2", "NCSTN_2", Amplicon ) ) %>%
	mutate( Amplicon = factor( Amplicon, levels=c( "18S", "NCSTN_1", "NCSTN_2" ) ) ) %>%
	mutate( Primer = str_replace( Primer, "\\.", " " ) ) %>%
	mutate( Primer = factor( Primer, levels=c( "18S", "NCSTN F1/R1", "NCSTN F2/R2" ) ) )

summary( shrna_rtqpcr )
```

## Generate values with error propagation

### Apply propagation
```{r prop_errors}
kd_stats <- shrna_rtqpcr %>%
	group_by( Cell_Line, Construct, Amplicon, Primer ) %>%
	dplyr::summarize( n=length( Cq ),
									 mean = mean( Cq ),
									 sd = sd( Cq ) )

kd_dCq <- ddply( kd_stats, c("Cell_Line", "Construct" ), .fun=deltaCqs, meanCol="mean" )

kd_ddCq <- ddply( kd_dCq, c( "Cell_Line", "Amplicon" ), .fun=deltaCqs, refCol="Construct", reference="control" ) %>%
	mutate( foldchange_mean = 2 ^ ( -1 * mean ) ) %>%
	mutate( foldchange_sd = log(2) * foldchange_mean * sd )

# This is an often overlooked point. All of these measurements have error.
# This includes the reference gene measurements and the exponentiation.
# Propagating these errors accurately incorporates this uncertainty.

kd_ddCq

summary( kd_ddCq )
```

```{r get18Srange}
rects_for_18S <- filter( kd_stats, Amplicon == "18S" ) %>%
	ddply( ., c( "Cell_Line", "Construct" ), .fun=deltaCqs, meanCol="mean", include_ref=TRUE ) %>%
	ddply( ., c( "Cell_Line", "Amplicon" ), .fun=deltaCqs, refCol="Construct", reference="control" ) %>%
	mutate( foldchange_mean = 2 ^ ( -1 * mean ) ) %>%
	mutate( foldchange_sd = log(2) * foldchange_mean * sd ) %>%
	mutate( Construct = as.character( Construct ) ) %>%
	mutate( Construct = factor( Construct, levels=c("A06", "A07", "A08", "A09", "A10") ) ) %>%
	mutate( xstart = as.integer( Construct ) - 0.20 ) %>%
	mutate( xend = as.integer( Construct ) + 0.20 ) %>%
	mutate( ystart = foldchange_mean - foldchange_sd ) %>%
	mutate( yend = foldchange_mean + foldchange_sd ) %>%
	select( Cell_Line, Construct, xstart, xend, ystart, yend )
```

```{r RTqPCR_prepuro_shRNA}
ggplot( kd_ddCq, aes( x=Construct, y=foldchange_mean, shape=Amplicon ) ) +
  facet_wrap( ~Cell_Line, ncol=2 ) +
  xlab( "\nshRNA Knockdown Construct" ) +
  ylab( "NCSTN Relative Expression\n" ) +
  theme_bw() +
  scale_y_continuous( breaks=seq( 0,1.25, by=0.25 ), limits = c( 0, 1.35 ) ) +
  scale_colour_manual( values=cbPalette ) +
  gg_no_x_grid +
	theme( legend.position="top" ) +
	gg_bigger_texts +
  geom_abline( intercept=1.0, slope=0, lty=2 ) +
	labs( shape="Amplicon Tested" ) +
	geom_point( size=3.5, position=position_dodge( 0.3 ) ) +
	geom_errorbar( aes( ymin = foldchange_mean - foldchange_sd, ymax = foldchange_mean + foldchange_sd ), width=0.2, position=position_dodge( 0.3 ), lwd=1.02 ) +
	geom_rect( data=rects_for_18S,
						 aes(
						 	xmin = xstart,
						 	xmax = xend,
						 	ymin = ystart,
						 	ymax = yend ),
						 colour="grey", alpha=0.25, inherit.aes = FALSE ) 
```

## sessionInfo
```{r session_information}
Sys.time()

getwd()
  
sessionInfo()
```

