---
title: "NCSTN shRNA knockdown growth_curves"
author: "E. Roberson"
date: "March 5, 2018"
output: html_document
---

```{r libraries}
library( plyr )
library( dplyr )
library( ggplot2 )
library( reshape2 )
library( stringr )
library( readr )
library( tidyr )
library( cowplot )
library( purrr )
library( broom )
```

```{r source_it}
source( here::here( 'code', "ncstn_knockdown_fxns.R" ) )
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message=FALSE,
	fig.path=paste0( output_figure_rel_dir, "/" ),
	fig.keep='all',
	dpi=300,
	fig.width=11,
	fig.height=8.5 )
```

```{r input}
raw <- read_csv( knockdown_growth_curve, col_names=TRUE ) %>%
	mutate( Day = paste0( "Day_", Day ) ) %>%
	mutate( Day = factor( Day ) ) %>%
	mutate( CellLine = factor( CellLine ) ) %>%
	mutate( Day = factor( Day ) ) %>%
	mutate( Knockdown = factor( Knockdown ) )

summary( raw )
```

## Background subtract
Now remove the background from each day measurement in each category.

```{r bg_sub}

bg_sub_fxn <- function( input, BlankCol="Knockdown" )
{
  blank.data = subset( input, Knockdown == "Blank" )[,"R1"]
  
  raw.data = subset( input, Knockdown != "Blank" )
  
  return( data.frame( Knockdown=raw.data$Knockdown, raw.data[,c("R1","R2","R3")] - blank.data ) )
}

raw.bg.sub <- ddply( .data=raw, .variables=c( "CellLine", "Day" ), .fun=bg_sub_fxn )

raw.bg.sub
```

## Calculate summary statistics
The background subtracted data can be summarized.

```{r make_summary_data}
dat.melt <- melt( raw.bg.sub ) %>%
	mutate( Knockdown = as.character( Knockdown ) ) %>%
	mutate( shRNA = Knockdown ) %>%
	mutate( shRNA = str_replace( shRNA, "Luciferase", "shLuc" ) ) %>%
	mutate( shRNA = factor( shRNA, levels=c( "shLuc", "A08" ) ) ) %>%
	mutate( plotDay = as.integer( Day ) )
summary( dat.melt )

dat.summary <- dat.melt %>%
	group_by( CellLine, Day, shRNA ) %>%
	dplyr::summarize( 
		mean = mean( value, na.rm=TRUE ),
		sd = sd( value, na.rm=TRUE ),
		n = length( value ) ) %>%
	mutate( plotDay = as.integer( Day ) )

dat.summary
```

## Plot data using ggplot2

```{r hek001_growth_curve}
asterisk.factor = 6
asterisk.offset = 0.005

hek001.curve <- dat.summary %>%
	filter( CellLine == "HEK001" ) %>%
	ggplot( ., aes( x=plotDay, y=mean, group=shRNA, shape=shRNA, colour=shRNA ) ) +
	scale_color_manual( values = cbPalette ) +
	geom_point( size=2.5, position=position_dodge( 0.3 ) ) +
	geom_errorbar( aes( ymin = mean - sd, ymax = mean + sd ), width=0.2, position=position_dodge( 0.3 ), lwd=1.02 ) +
	theme_bw() +
	scale_y_continuous( breaks=seq( 0, 0.25, by=0.05 ), limits=c( 0, 0.25 ) ) +
	scale_x_continuous( breaks=seq( 1, 7 ), limits=c(0.75, 7.25) ) +
	scale_fill_manual( values=cbPalette ) +
	gg_bigger_texts +
	gg_no_x_grid +
	xlab( "Day (HEK001)" ) +
	ylab( "Absorbance\n" ) +
	theme( legend.position = "none" ) +
	# day 4
	geom_segment( aes( x=3.80, xend=4.2, y=0.237, yend=0.237 ), colour="black" ) +
	geom_text( aes( x=4, y=asterisk.offset+0.237 ), label="*", colour="black", size=asterisk.factor, hjust=0.5 ) +

	# day 5
	geom_segment( aes( x=4.80, xend=5.2, y=0.210, yend=0.210 ), colour="black" ) +
	geom_text( aes( x=5, y=asterisk.offset+0.210 ), label="*", colour="black", size=asterisk.factor, hjust=0.5 ) +
	
	# day 6
	geom_segment( aes( x=5.80, xend=6.2, y=0.14, yend=0.14 ), colour="black" ) +
	geom_text( aes( x=6, y=asterisk.offset+0.14 ), label="*", colour="black", size=asterisk.factor, hjust=0.5 )
	
hek001.curve
```

```{r hek293_growthcurve}
hek293.curve <- dat.summary %>%
	filter( CellLine == "HEK293" ) %>%
		ggplot( ., aes( x=plotDay, y=mean, group=shRNA, shape=shRNA, colour=shRNA ) ) +
	scale_color_manual( values = cbPalette ) +
	geom_point( size=2.5, position=position_dodge( 0.3 ) ) +
	geom_errorbar( aes( ymin = mean - sd, ymax = mean + sd ), width=0.2, position=position_dodge( 0.3 ), lwd=1.02 ) +
	  theme_bw() +
	  scale_y_continuous( breaks=seq( 0, 0.6, by=0.1 ), limits=c( 0, 0.6 ) ) +
		scale_x_continuous( breaks=seq( 1, 7 ), limits=c(0.75,7.25) ) +
	  scale_fill_manual( values=cbPalette ) +
		gg_bigger_texts +
#		gg_no_grid +
	gg_no_x_grid +
		xlab( "Day (HEK293)" ) +
	  ylab( "Absorbance\n" ) +
		theme( legend.position = "none" ) +

	# day 5
	geom_segment( aes( x=4.80, xend=5.2, y=0.58, yend=0.58 ), colour="black" ) +
	geom_text( aes( x=5, y=asterisk.offset+0.58 ), label="*", colour="black", size=asterisk.factor, hjust=0.5 ) +
	
	# day 6
	geom_segment( aes( x=5.80, xend=6.2, y=0.535, yend=0.535 ), colour="black" ) +
	geom_text( aes( x=6, y=asterisk.offset+0.535 ), label="*", colour="black", size=asterisk.factor, hjust=0.5 )

hek293.curve
```

```{r cowplot_growthcurves}
plt.curves = plot_grid( hek001.curve, hek293.curve, labels=c( "(a)", "(b)" ), nrow=2 )
legend = get_legend( hek001.curve + theme( legend.position = "right" ) )

plot_grid( plt.curves, legend, rel_widths = c( 2, 0.25 ) )
```

```{r ttest}
growth.stat <- dat.melt %>%
	group_by( ., CellLine, Day ) %>%
	nest( . ) %>%
	mutate( ., nested_ttest = map( data, ~ t.test( value~shRNA, data=.x ) ) ) %>%
	select( ., -data ) %>%
	mutate( ., glance_ttest = map( nested_ttest, glance ) ) %>%
	mutate( ., pvalue = map_dbl( glance_ttest, "p.value" ) ) %>%
	select( ., CellLine, Day, pvalue ) %>%
	write_csv( ., path = file.path( output_rel_dir, "ttest_growth_curve.csv" ) )
```

```{r foldchanges}
fc_function <- function( input_df, wt="shLuc", other="A08" ) {
	wt.index <- which( input_df$shRNA == wt )
	other.index <- which( input_df$shRNA == other )
	
	wt.mean <- input_df[ wt.index, "mean" ]
	wt.sd <- input_df[ wt.index, "sd" ]
	other.mean <- input_df[ other.index, "mean" ]
	other.sd <- input_df[ other.index, "sd" ]
	
	fc.mean <- other.mean / wt.mean
	
	fc.sd <- sqrt( ( wt.sd / wt.mean )^2 + (other.sd / other.mean)^2 )
	fc.sd <- fc.sd * abs( fc.mean )
	
	return( data.frame( Foldchange = fc.mean, FoldchangeSD=fc.sd ) )
}

calc.fcs <- ddply( .data = dat.summary, .variables = c( "CellLine", "Day" ), .fun = fc_function )
```

```{r combine}
merge( growth.stat, calc.fcs ) %>%
	write_csv( file.path( output_rel_dir, "growth_curve_stats.csv" ) )
```

# Program info
```{r session_information}
Sys.time()

getwd()
  
sessionInfo()
```
