---
title: "Heterozygous deleted edited cell line ligand stimulation"
author: "E. Roberson"
date: "March 11, 2018"
output: html_document
---

```{r libraries}
library( here )
library( plyr )
library( dplyr )
library( ggplot2 )
library( reshape2 )
library( stringr )
library( readr )
library( tidyr )
library( tibble )
```

```{r source_it}
source( here::here( 'code', "ncstn_knockdown_fxns.R" ) )
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message=FALSE,
	fig.path=paste0( output_figure_rel_dir, "/" ),
	fig.keep='all',
	dpi=300,
	fig.width=11,
	fig.height=8.5 )
```

## Import data
```{r read_data}
indat <- read_csv( knockout_stimulate_luciferase, col_names=TRUE ) %>%
	mutate( Line = Edit ) %>%
	mutate( Line = str_replace( Line, pattern = "C_T_48", replacement = "Het. Deletion" ) ) %>%
	mutate( Line = factor( Line, levels=c( "WT", "Het. Deletion" ) ) ) %>%
	mutate( Treatment = str_replace( Treatment, "TNFA", "TNF" ) ) %>%
	filter( Treatment %in% c( "None", "TNF" ) ) %>%
	mutate( Treatment = factor( Treatment, levels=c( "None", "TNF" ) ) ) %>%
	select( -Edit, -Element )

factors <- indat[ , c( "Line", "Treatment" ) ]
firefly <- indat[ , grep("firefly", colnames(indat)) ]
renilla <- indat[ , grep("Renilla", colnames(indat)) ]

firefly

renilla

luc.dat <- cbind( factors, firefly / renilla )

luc.dat
```

## Reshape the data

```{r reshape}
luc.melt <- melt( luc.dat ) %>%
	mutate( value = log2( value ) ) # RELAX the log2 is on purpose
# plotting out the RFU data shows a strong mean-variance relationship
# which knocks out doing any sort of normality assumption
# but we can log2 transform the data to take care of that.
# helps with both the visualization and the Tukey HSD test.
```

## Summarize data
```{r melt_summary}
luc.melt.summarized <- luc.melt %>%
	group_by( Line, Treatment ) %>%
	dplyr::summarize(
		mean = mean( value, na.rm=TRUE ),
		sd = sd( value, na.rm=TRUE ),
		n = length( value )
	)

luc.melt.summarized
```

## Plot the resulting data
```{r hek293_genome_edit_stimulation}
plain_plot <- ggplot( luc.melt, aes( x=Treatment, y=value, group=Line, shape=Line, colour=Line ) ) +
	geom_point( size=4, position=position_jitterdodge(0.3)  ) +
	scale_colour_manual( values = cbPalette[c(4,2)] ) +
	xlab( "\nLigand Treatment" ) +
	ylab( parse( text="log[2]~(RFU)" ) ) +
	theme_bw() +
	gg_bigger_texts +
	theme( legend.position = "top" ) +
	gg_center_title +
	guides( shape=guide_legend( title="HEK293 Line" ), color=guide_legend( title="HEK293 Line" ) )

plain_plot

actual_coords <- ggplot_build( plain_plot )$data[[1]]

get_limits <- actual_coords %>%
	filter( x > 1.5 ) %>%
	group_by( .data = ., group ) %>%
	summarise(
		xmean = mean( x )
	)

# add significance segments
# TNF section
tnf_x_start <- 1.75
tnf_x_end <- 2.25

tnf_x_group_start <- min( get_limits$xmean )
tnf_x_group_end <- max( get_limits$xmean )

tnf_y_low <- 8.65
tnf_y_highest <- 9.45
tnf_y_high <- 9.3

asterisk_vert_offset <- 0.08
asterisk_size_factor <- 5

between_low_x_start <- 0.75
between_low_x_end <- 1.25
between_low_y <- 6.75

between_y_highest <- 9.92
tnf_y_between <- 9.73

plain_plot +
	gg_no_x_grid +
	scale_y_continuous( limits=c( 0, 10.2 ) ) +
	# between
	geom_segment( aes( x=between_low_x_start, xend=between_low_x_end, y=between_low_y, yend=between_low_y ), colour="black" ) +
	geom_segment( aes( x=( between_low_x_start + between_low_x_end ) / 2, xend=( between_low_x_start + between_low_x_end ) / 2, y=between_low_y, yend=between_y_highest ), colour="black" ) +
	geom_segment( aes( x=( between_low_x_start + between_low_x_end ) / 2, xend=( tnf_x_start + tnf_x_end ) / 2, y=between_y_highest, yend=between_y_highest ), colour="black" ) +
	geom_segment( aes( x=tnf_x_start, xend=tnf_x_end, y=tnf_y_between, yend=tnf_y_between ), colour="black" ) +
	geom_segment( aes( x=( tnf_x_start + tnf_x_end ) / 2, xend=( tnf_x_start + tnf_x_end ) / 2, y=tnf_y_between, yend=between_y_highest), colour="black" ) +
	geom_text( aes( x = ( between_low_x_start + tnf_x_end ) / 2, y=between_y_highest + asterisk_vert_offset ), label = "*", colour="black", size=asterisk_size_factor, hjust=0.5 ) +
	
	# TNF
	geom_segment( aes( x=tnf_x_group_start, xend=tnf_x_group_start, y=tnf_y_low, yend=tnf_y_highest ), colour="black" ) +
	geom_segment( aes( x=tnf_x_group_start, xend=tnf_x_group_end, y=tnf_y_highest, yend=tnf_y_highest ), colour="black" ) +
	geom_segment( aes( x=tnf_x_group_end, xend=tnf_x_group_end, y=tnf_y_highest, yend=tnf_y_high ), colour="black" ) +
	geom_text( aes( x = 2.0, y=tnf_y_highest+asterisk_vert_offset ), label = "*", colour="black", size=asterisk_size_factor, hjust=0.5 )
```

## Calculate significance of differences
Analysis of variance + Tukey Honest Simple Differences will take into account the different tests and interactions, and give us p-values for the differences.

```{r calc_fold_changes}
luc.melt.summarized <- luc.melt.summarized %>%
	mutate( tukey_id = paste( Line, Treatment, sep=":" ) ) %>%
	as.data.frame( . )
rownames( luc.melt.summarized ) = luc.melt.summarized$tukey_id
```

```{r TukeyHSD, message=FALSE}
tukey_hsd <- aov( value ~ Line*Treatment, data=luc.melt ) %>%
	TukeyHSD( . )

tukey_hsd

tukey_fcs <- ldply( .data = rownames( tukey_hsd[['Line:Treatment']] ), .fun = luciferase_foldchange, luc.melt.summarized )

tukey_hsd[['Line:Treatment']] %>%
	as.data.frame( . ) %>%
	rownames_to_column( ., "tukey_id" ) %>%
	merge( ., tukey_fcs ) %>%
	mutate( ., Comparison = tukey_id ) %>%
	select( -tukey_id ) %>%
	separate( ., Comparison, into=c( "Side1", "Side2" ), sep="\\-" ) %>%
	separate( ., Side1, into=c( "Line_LHS", "Treatment_LHS" ) , sep="\\:" ) %>%
	separate( ., Side2, into=c( "Line_RHS", "Treatment_RHS" ), sep="\\:" ) %>%
	select( Line_LHS, Treatment_LHS, Line_RHS, Treatment_RHS, diff, lwr, upr, `p adj`, Foldchange_mean, Foldchange_sd ) %>%
	write_csv( ., path = file.path( output_rel_dir, "tukey_hsd_GenomeEdit_luciferase.csv" ) )
```

## sessionInfo
```{r sessionInfo}
Sys.time()

getwd()

sessionInfo()
```
